version: "3.9"

services:
  redis:
    image: redis:6.2.6
    ports:
      - 6379:6379
    volumes:
      - ./docker/volumes/redis/gtdzero:/data
    networks:
      - back-tier

  postgres:
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gtdzero
    ports:
      - 5432:5432
    volumes:
      - ./docker/volumes/pg/gtdzero:/var/lib/postgresql/data
    networks:
      - back-tier

  srv:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_URL=redis:6379
      - DATABASE_URL=postgres://username:password@postgres:5432/gtdzero
      - ACCESS_SECRET=${ACCESS_SECRET:-access-secret}
      - REFRESH_SECRET=${REFRESH_SECRET:-refresh-secret}
      - GIN_MODE=${GIN_MODE:-debug}
    ports:
      - 8080:8080
    networks:
      - back-tier

networks:
  back-tier:
